---
driver:
  name: vagrant
#  provider: vmware_fusion
  provider: virtualbox
  ssh:
    pty: true
  customize:
    memory: 1024
    natdnshostresolver1: 'on'
    natdnsproxy1: 'on'

provisioner:
  name: chef_solo
  roles_path: provision/chef/roles
  data_bags_path:  provision/chef/data_bags
  cookbook_path:
    - provision/chef/cookbooks
    - provision/chef/vendor-cookbooks

platforms:
  - name: centos
    driver:
      box: tompscanlan/headless-centos
    run_list:
      - role[izanamee-headless]
  - name: ubuntu
    driver:
      box: tompscanlan/headless-ubuntu
    run_list:
      - role[izanamee-headless]

suites:
  - name: mysql
    includes:
      - centos
      - ubuntu
    run_list:
      - role[mysql_wrap]

  - name: jenkins
    includes:
      - centos
      - ubuntu
    run_list:
      - role[jenkinsonar]
    attributes:
      jenkins-job:
        job-templates:
          test_sonar: test_sonar.xml.erb

  - name: flamegraph
    includes:
      - ubuntu
      - centos
    run_list:
      - role[flamegraph]

  - name: headless
    includes:
      - ubuntu
      - docker
      - centos
    run_list:
      - role[izanamee-headless]

  - name: desktop
    includes:
      - ubuntu
      - docker
    run_list:
      - role[izanamee-desktop]
