---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo
  roles_path: provision/chef/roles
  data_bags_path:  provision/chef/data_bags
  cookbook_path:
    - provision/chef/cookbooks
    - provision/chef/vendor-cookbooks

platforms:
  - name: trusty-headless-vbox
    driver:
      box: izanamee/headless
      provider: virtualbox
  - name: trusty-desktop-vbox
    driver:
      box: izanamee/desktop
      provider: virtualbox

suites:
  - name: desktop
    run_list:
      - role[izanamee-desktop]
    customize:
      memory: 2048
    includes:
      - trusty-desktop-vbox
    attributes:
  - name: headless
    run_list:
      - role[izanamee-headless]
    attributes:
    includes:
      - trusty-headless-vbox
  - name: builder
    run_list:
      - role[docker-builder]
    attributes:
    includes:
      - trusty-headless-vbox
