---
driver:
  name: vagrant
  provider: vmware_fusion
#  provider: virtualbox
  customize:
    memory: 1024
    natdnshostresolver1: 'on'
    natdnsproxy1: 'on'

provisioner:
  name: chef_solo
  roles_path: provision/chef/roles
  data_bags_path:  provision/chef/data_bags
  cookbook_path:
    - provision/chef/cookbooks
    - provision/chef/vendor-cookbooks
  # you can set these to a valid proxy if
  # running tests behind a proxy
  # http_proxy: http://192.168.0.3:3128
  # https_proxy: http://192.168.0.3:3128

platforms:
  - name: centos
    driver:
      box: tompscanlan/headless-centos
      gui: true
    ssh:
      pty: true
    run_list:
      - role[izanamee-headless]
  - name: ubuntu
    driver:
      box: tompscanlan/headless-ubuntu
      gui: true
    run_list:
      - role[izanamee-headless]
  - name: ubuntu-docker
    driver:
      name: docker
      platform: ubuntu
      image: jpetazzo/dind:latest

suites:
  - name: mysql
    includes:
      - centos
      - ubuntu
    run_list:
      - role[mysql]

  - name: jenkins
    includes:
      - centos
      - ubuntu
    run_list:
      - role[jenkinsonar]
    attributes:
      jenkins-job:
        job-templates:
          test_sonar: test_sonar.xml.erb

  - name: flamegraph
    includes:
      - ubuntu
      - centos
    run_list:
      - role[flamegraph]

  - name: headless
    includes:
      - ubuntu-docker
    run_list:
      - role[docker-izanamee-headless]

  - name: headless
    includes:
      - ubuntu
      - centos
    run_list:
      - role[izanamee-headless]

  - name: desktop
    includes:
      - ubuntu
    run_list:
      - role[izanamee-desktop]
