---
driver:
  name: vagrant
  provider: vmware_fusion
  ssh:
    pty: true
  customize:
    memory: 1024

provisioner:
  name: chef_solo
  roles_path: provision/chef/roles
  data_bags_path:  provision/chef/data_bags
  cookbook_path:
    - provision/chef/cookbooks
    - provision/chef/vendor-cookbooks

platforms:
  - name: centos
    driver:
      box: tompscanlan/centos-headless
      customize:
        memory: 256
    run_list:
      - role[izanamee-headless-centos]
  - name: ubuntu
    driver:
      box: tompscanlan/headless
      customize:
        memory: 256
    run_list:
      - role[izanamee-headless]
  - name: ubuntu-desktop
    driver:
      box: tompscanlan/desktop
    run_list:
      - role[izanamee-desktop]

suites:
  - name: packer-builder
    includes:
      - ubuntu-desktop
    run_list:
      - role[jenkins-master]
    customize:
      memory: 2048

  - name: jenkins
    includes:
      - centos
      - ubuntu
    run_list:
      - role[jenkins-headless]
    customize:
      memory: 2048

  - name: builder
    run_list:
      - role[docker-builder]
    attributes:
    includes:
      - trusty-headless-vbox
#  - name: centos-desktop
#    driver:
#      box: izanamee/centos-headless
#    run_list:
#      - role[izanamee-desktop-centos]

  - name: flamegraph
    includes:
      - centos
      - ubuntu
      - ubuntu-desktop
    run_list:
      - role[flamegraph]

  - name: headless
    includes:
      - centos
      - ubuntu

  - name: desktop
    includes:
      - ubuntu-desktop

  - name: sonar
    includes:
      - centos
      - ubuntu
      - ubuntu-desktop
    run_list:
      - role[jenkins-headless]
    attributes:
      jenkins-job:
        job-templates:
          test_sonar: test_sonar.xml.erb
