#
# Ops-Pipeline - Templates for automating the production and consumption of images
# and containers.
#
# Copyright 2016 Capital One Services, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ansible galaxy file.
# run ansible-galaxy install -r galaxy.yml

# from galaxy
- src: https://github.com/tompscanlan/mysql
  path: provision/ansible/vendor-roles/

# from github
#- src: https://github.com/bennojoy/nginx

# from github installing to a relative path
#- src: https://github.com/bennojoy/nginx
#  path: vagrant/roles/

# from github, overriding the name and specifying a specific tag
#- src: https://github.com/bennojoy/nginx
#  version: master
#  name: nginx_role

# from a webserver, where the role is packaged in a tar.gz
#- src: https://some.webserver.example.com/files/master.tar.gz
#  name: http-role

# from bitbucket, if bitbucket happens to be operational right now :)
#- src: git+http://bitbucket.org/willthames/git-ansible-galaxy
#  version: v1.4

# from bitbucket, alternative syntax and caveats
#- src: http://bitbucket.org/willthames/hg-ansible-galaxy
#  scm: hg
